<?php

/**
 * Created by PhpStorm.
 * User: sl
 * Date: 2017/11/30
 * Time: 下午4:54
 * Hope deferred makes the heart sick,but desire fulfilled is a tree of life.
 */
namespace App\Component;
use Symfony\Component\HttpFoundation\Request as SymfonyRequest;

class Request extends SymfonyRequest
{
    /**
     * @param bool $asResource
     * @return string
     */
    public function getContent($asResource = false)
    {
        parent::getContent($asResource); // TODO: Change the autogenerated stub
        if (null == $this->content || false === $this->content) {
            $this->content = \Core\Http\Request::getInstance()->getBody()->__toString();
        }
        return $this->content;
    }
}